### ISSUE TITLE
wr.s3.to_parquet raises AccessDenied error when writing to catalog in another account

### ISSUE THREAD

**Issue by willsmith28** [aws/aws-sdk-pandas#1657]
### Describe the bug

Our organization is looking into using multiple accounts in our organization to extend the total number of glue dataset partitions we can use. My IAM user account has been granted permissions to create tables and databases in the other catalog and I can verify with the aws cli, but `wr.s3.to_parquet` fails with an Access Denied Error.

### How to Reproduce

```
# database already exists
database = "test_cross_catalog_db"
table = "cross_catalog_table"
catalog_id_in_another_account = "123456789012"
# credentials in ~/.aws/credentials have access
session = boto3.Session(region_name="eu-central-1")
df = pd.DataFrame({"val": [1.0,2.0,3.0]})
# fails with Access Denied Error
wr.s3.to_parquet(
    df=df,
    path=f"s3://bucket/{database}/{table}",
    compression="snappy",
    boto3_session=session,
    dataset=True,
    mode="append",
    schema_evolution=False,
    database=database,
    table=table,
    catalog_id=catalog_id_in_another_account,
)
```
results in the following traceback and no table in the other catalog
```
Exception ignored in: <function _S3ObjectBase.__del__ at 0x7ff6b5be29d0>
Traceback (most recent call last):
  File "/home/will/miniconda3/envs/tsawsdatahub/lib/python3.9/site-packages/awswrangler/s3/_fs.py", line 243, in __del__
    self.close()
  File "/home/will/miniconda3/envs/tsawsdatahub/lib/python3.9/site-packages/awswrangler/s3/_fs.py", line 474, in close
    _utils.try_it(
  File "/home/will/miniconda3/envs/tsawsdatahub/lib/python3.9/site-packages/awswrangler/_utils.py", line 343, in try_it
    return f(**kwargs)
  File "/home/will/miniconda3/envs/tsawsdatahub/lib/python3.9/site-packages/botocore/client.py", line 514, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/will/miniconda3/envs/tsawsdatahub/lib/python3.9/site-packages/botocore/client.py", line 938, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the PutObject operation: Access Denied
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/will/miniconda3/envs/tsawsdatahub/lib/python3.9/site-packages/awswrangler/_config.py", line 461, in wrapper
    return function(**args)
  File "/home/will/miniconda3/envs/tsawsdatahub/lib/python3.9/site-packages/awswrangler/s3/_write_parquet.py", line 637, in to_parquet
    paths, partitions_values = _to_dataset(
  File "/home/will/miniconda3/envs/tsawsdatahub/lib/python3.9/site-packages/awswrangler/s3/_write_dataset.py", line 261, in _to_dataset
    paths = func(
  File "/home/will/miniconda3/envs/tsawsdatahub/lib/python3.9/site-packages/awswrangler/s3/_write_parquet.py", line 188, in _to_parquet
    writer.write_table(table)
  File "/home/will/miniconda3/envs/tsawsdatahub/lib/python3.9/contextlib.py", line 126, in __exit__
    next(self.gen)
  File "/home/will/miniconda3/envs/tsawsdatahub/lib/python3.9/site-packages/awswrangler/s3/_write_parquet.py", line 75, in _new_writer
    writer.close()
  File "/home/will/miniconda3/envs/tsawsdatahub/lib/python3.9/contextlib.py", line 126, in __exit__
    next(self.gen)
  File "/home/will/miniconda3/envs/tsawsdatahub/lib/python3.9/site-packages/awswrangler/s3/_fs.py", line 588, in open_s3_object
    s3obj.close()
  File "/home/will/miniconda3/envs/tsawsdatahub/lib/python3.9/site-packages/awswrangler/s3/_fs.py", line 474, in close
    _utils.try_it(
  File "/home/will/miniconda3/envs/tsawsdatahub/lib/python3.9/site-packages/awswrangler/_utils.py", line 343, in try_it
    return f(**kwargs)
  File "/home/will/miniconda3/envs/tsawsdatahub/lib/python3.9/site-packages/botocore/client.py", line 514, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/will/miniconda3/envs/tsawsdatahub/lib/python3.9/site-packages/botocore/client.py", line 938, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the PutObject operation: Access Denied
```
The following aws cli command will successfully create an equivalent table in the other catalog

```
aws glue create-table \
    --database-name test_cross_catalog_db \
    --table-input  '{"Name":"cross_catalog_table",  
        "StorageDescriptor":{ 
            "Columns":[ 
                {"Name":"val", "Type":"double"} 
            ], 
            "Location":"s3://bucket/test_cross_catalog_db/cross_catalog_table", 
            "InputFormat": "org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat", 
            "OutputFormat": "org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat", 
            "Compressed": true, 
            "NumberOfBuckets": -1, 
            "SerdeInfo": { 
                "SerializationLibrary": "org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe", 
                "Parameters": { 
                    "serialization.format": "1" 
                } 
            }, 
            "BucketColumns": [], 
            "SortColumns": [], 
            "Parameters": { 
                "CrawlerSchemaDeserializerVersion": "1.0", 
                "classification": "parquet", 
                "compressionType": "snappy", 
                "typeOfData": "file" 
            }, 
            "StoredAsSubDirectories": false 
        }, 
        "TableType": "EXTERNAL_TABLE",
        "Parameters":{ 
            "classification":"parquet"} 
        }' \
    --region eu-central-1 \
    --catalog-id 123456789012
```
even after creating the table the above python snippet will still fail with the following traceback

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/will/miniconda3/envs/tsawsdatahub/lib/python3.9/site-packages/awswrangler/_config.py", line 461, in wrapper
    return function(**args)
  File "/home/will/miniconda3/envs/tsawsdatahub/lib/python3.9/site-packages/awswrangler/s3/_write_parquet.py", line 637, in to_parquet
    paths, partitions_values = _to_dataset(
  File "/home/will/miniconda3/envs/tsawsdatahub/lib/python3.9/site-packages/awswrangler/s3/_write_dataset.py", line 261, in _to_dataset
    paths = func(
  File "/home/will/miniconda3/envs/tsawsdatahub/lib/python3.9/site-packages/awswrangler/s3/_write_parquet.py", line 188, in _to_parquet
    writer.write_table(table)
  File "/home/will/miniconda3/envs/tsawsdatahub/lib/python3.9/contextlib.py", line 126, in __exit__
    next(self.gen)
  File "/home/will/miniconda3/envs/tsawsdatahub/lib/python3.9/site-packages/awswrangler/s3/_write_parquet.py", line 75, in _new_writer
    writer.close()
  File "/home/will/miniconda3/envs/tsawsdatahub/lib/python3.9/contextlib.py", line 126, in __exit__
    next(self.gen)
  File "/home/will/miniconda3/envs/tsawsdatahub/lib/python3.9/site-packages/awswrangler/s3/_fs.py", line 588, in open_s3_object
    s3obj.close()
  File "/home/will/miniconda3/envs/tsawsdatahub/lib/python3.9/site-packages/awswrangler/s3/_fs.py", line 474, in close
    _utils.try_it(
  File "/home/will/miniconda3/envs/tsawsdatahub/lib/python3.9/site-packages/awswrangler/_utils.py", line 343, in try_it
    return f(**kwargs)
  File "/home/will/miniconda3/envs/tsawsdatahub/lib/python3.9/site-packages/botocore/client.py", line 514, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/will/miniconda3/envs/tsawsdatahub/lib/python3.9/site-packages/botocore/client.py", line 938, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the PutObject operation: Access Denied
```

### Expected behavior

For `wr.s3.to_parquet` to create tables in the other account just like the aws cli

### OS

Win/Linux

### Python version

3.9

### AWS SDK for pandas version

2.17.0

**Comment by jaidisido** [comment]
The AccessDenied exception is raised against the S3 PutObject permission, not against creating a table in the Glue catalog (i.e. glue.CreateTable). Is your IAM role allowed to PUT S3 objects cross account?

**Comment by willsmith28** [comment]
This is a s3 permission issue, My IAM role should have had access to write to the bucket, but I had to be given full admin access to s3 for the `aws s3 cp` command to succeed. 

Thank you for you time!
