### ISSUE TITLE
How to catch ValidationException in timestream.write?

### ISSUE THREAD

**Issue by mdavis-xyz** [aws/aws-sdk-pandas#2031]
I'm writing data with [wr.timestream.write](https://aws-sdk-pandas.readthedocs.io/en/stable/stubs/awswrangler.timestream.write.html#awswrangler.timestream.write).

I'm getting an error:

```
[ERROR] ValidationException: An error occurred (ValidationException) when calling the WriteRecords operation: Timestream only supports finite IEEE Standard 754 floating point precision for double measure value type.
Traceback (most recent call last):
  File "/opt/python/tenergy/logs/decorator.py", line 39, in wrapper
    ret = func(event=event, context=context, **kwargs)
  File "/var/task/main.py", line 35, in main
    write_turbines(df)
  File "/var/task/main.py", line 191, in write_turbines
    rejected_records = wr.timestream.write(
  File "/opt/python/awswrangler/timestream.py", line 284, in write
    res: List[List[Any]] = list(
  File "/var/lang/lib/python3.8/concurrent/futures/_base.py", line 619, in result_iterator
    yield fs.pop().result()
  File "/var/lang/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/var/lang/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/var/lang/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/python/awswrangler/timestream.py", line 78, in _write_batch
    _utils.try_it(
  File "/opt/python/awswrangler/_utils.py", line 334, in try_it
    return f(**kwargs)
  File "/var/runtime/botocore/client.py", line 391, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/runtime/botocore/client.py", line 719, in _make_api_call
    raise error_class(parsed_response, operation_name)
```

I don't know what this means. As a first step, I want to use `try/except` to catch this exception in my code, and then print it out.

How do I catch a `ValidationException`?

That's not a standard exception like `ValueError` or `TypeError`. It's not in `awswrangler.exceptions`, or even `boto3.client('timestream-writer').exceptions`. `wrangler.timestream.exceptions` doesn't exist.

So what class is this exception? 

(If you also know the cause of the error, that's would be nice too. But of course that's hard without the input data.)

**Comment by jaidisido** [comment]
From the log trace, the error is raised by botocore, so you should be able to try/catch it using their Error Handling logic:
https://boto3.amazonaws.com/v1/documentation/api/latest/guide/error-handling.html#catching-botocore-exceptions

As for the error itself, it's hard to debug without more details on the data, but I could find a similar SO [issue](https://stackoverflow.com/questions/65534087/write-null-measure-values-to-aws-timestream).

**Comment by mdavis-xyz** [comment]
Ah I see. I did try to catch the error like that. I just first tested in a console and found that the error wasn't defined in botocore. That's because it only becomes defined *after* you instantiate the client.

Yes that other issue looks similar, and is probably the answer.

**Comment by mdavis-xyz** [comment]
Oh, actually botocore has a `ValidationError`, but not a `ValidationException`. Hopefully it's just the lazy aspect of botocore and it will appear once I try it in my real code.
