### ISSUE TITLE
`ignore_index` in `wr.s3.read_parquet` uses metadata to generate the index (not ignoring it)

### ISSUE THREAD

**Issue by jmahlik** [aws/aws-sdk-pandas#2177]
### Describe the bug

When using `ignore_index` the pandas metadata is still used to attempt to [apply an index](https://github.com/aws/aws-sdk-pandas/blob/77017153c295e6f9d3ce2df3515d3a4ef4d85786/awswrangler/s3/_read_parquet.py#L239-L268). This can cause an issue when creating partitioned parquet files on a dataframe with a rangeindex. 

This is fixed in `3.0.0rc3`. 

This could be a bug in pyarrow since the entire index is saved in the metadata of each file vs. only the index for that particular file. Maybe that's intentional behavior, not sure.

Mostly opening this as research on https://github.com/aws/aws-sdk-pandas/issues/1775, using pyarrow directly seems to result in the correct behavior in this scenario.

### How to Reproduce

There's a lot of setup code but tried to make it directly runnable.

On 2.20.0 results in an invalid index being applied. On 3.0.0rc3 with removing `ignore_index` this works correctly and the data has a correct range index. The workaround for 2.x is to use `pa.Table.from_pandas(data, preserve_index=False)`.

```python
import pathlib

import awswrangler as wr
import boto3
from moto import mock_s3
import pandas as pd
import pyarrow as pa
import pyarrow.dataset as ds

os.environ["AWS_ACCESS_KEY_ID"] = "testing"
os.environ["AWS_SECRET_ACCESS_KEY"] = "testing"
os.environ["AWS_SECURITY_TOKEN"] = "testing"
os.environ["AWS_SESSION_TOKEN"] = "testing"


tmp_path = pathlib.Path("data")
output_path = tmp_path.joinpath("data")
output_path.mkdir(parents=True)

data = pd.DataFrame({"hello": range(10)})

# Write partitions based on number of rows
ds.write_dataset(
    pa.Table.from_pandas(data),
    format="parquet",
    base_dir=output_path,
    max_rows_per_file=1,
    max_rows_per_group=1,
)

# Same number of files as rows
files = os.listdir(output_path)
assert len(files) == len(data)
with mock_s3():
    session = boto3.Session(region_name="us-east-1")
    # Make a fake bucket and upload everything
    client = session.client("s3")
    bucket = "data"
    client.create_bucket(Bucket=bucket)
    path = f"s3://{bucket}/data/"

    for f in files:
        wr.s3.upload(
            local_file=os.path.join(str(output_path), f),
            path=f"{path}/{f}",
            boto3_session=session,
        )

    # All have been uploaded
    objects = wr.s3.list_objects(path, boto3_session=session)
    assert len(objects) == len(data)

    # Now try to read it back in
    df = wr.s3.read_parquet(path, boto3_session=session, ignore_index=True)
    print(df)
    print(df.index)
```

Stack trace from 2.x

```
INFO:botocore.credentials:Found credentials in environment variables.
Traceback (most recent call last):
  File "dir\tests\scripts\test_data_preprocessing.py", line 174, in <module>
    df = wr.s3.read_parquet(path, boto3_session=session, ignore_index=True)
  File "dir\.venv\lib\site-packages\awswrangler\s3\_read_parquet.py", line 794, in read_parquet
    dfs=_read_dfs_from_multiple_paths(
  File "dir\.venv\lib\site-packages\awswrangler\s3\_read.py", line 150, in _read_dfs_from_multiple_paths
    return list(df for df in executor.map(partial_read_func, paths, versions))
  File "dir\.venv\lib\site-packages\awswrangler\s3\_read.py", line 150, in <genexpr>
    return list(df for df in executor.map(partial_read_func, paths, versions))
  File "C:\Users\rm13\Python\Python310\lib\concurrent\futures\_base.py", line 621, in result_iterator
    yield _result_or_cancel(fs.pop())
  File "C:\Users\rm13\Python\Python310\lib\concurrent\futures\_base.py", line 319, in _result_or_cancel
    return fut.result(timeout)
  File "C:\Users\rm13\Python\Python310\lib\concurrent\futures\_base.py", line 451, in result
    return self.__get_result()
  File "C:\Users\rm13\Python\Python310\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
  File "C:\Users\rm13\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "dir\.venv\lib\site-packages\awswrangler\s3\_read_parquet.py", line 534, in _read_parquet
    df: pd.DataFrame = _arrowtable2df(
  File "dir\.venv\lib\site-packages\awswrangler\s3\_read_parquet.py", line 330, in _arrowtable2df
    df = _apply_index(df=df, metadata=metadata)
  File "dir\.venv\lib\site-packages\awswrangler\s3\_read_parquet.py", line 253, in _apply_index
    df.index = pd.RangeIndex(start=col["start"], stop=col["stop"], step=col["step"])
  File "dir\.venv\lib\site-packages\pandas\core\generic.py", line 5915, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas\_libs\properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "dir\.venv\lib\site-packages\pandas\core\generic.py", line 823, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "dir\.venv\lib\site-packages\pandas\core\internals\managers.py", line 227, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "dir\.venv\lib\site-packages\pandas\core\internals\base.py", line 70, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 1 elements, new values have 10 elements
```

### Expected behavior

Generate a rangindex based on the length of the dataframe, or just leave the dataframe alone. Since this is fixed in 3.0, likely no action needed. But would suggest avoiding altering the index in 3.0.

### OS

windows/linux

### Python version

3.9

### AWS SDK for pandas version

2.20.0 and 3.0.0rc3

**Comment by malachi-constant** [comment]
We are working towards releasing `3.0.0` in the next couple weeks, I think we should probably push users with this problem to use `3.x` unless there is some compelling reason users cannot upgrade and can't use the work around.

**Comment by jaidisido** [comment]
@jmahlik, I wanted to get your view on PR #2206 before we merge it please. The change is not directly related to the issue you opened here. However it does affect the default `ignore_index` behaviour.

In short, in the latest release (3.0.0) pandas index recovery is not enabled by default. That behaviour is controlled by the [ignore_metadata](https://arrow.apache.org/docs/python/generated/pyarrow.Table.html#pyarrow.Table.to_pandas) parameter in the to_pandas arrow method. We have set it to True by default which is a breaking change compared to 2.x (and default pandas behaviour). We wish to flip it back to False by default. Thanks!

**Comment by jmahlik** [comment]
For this specific case, master at 5ff743964ae12d37c6ee56fcab4246fe6aa0ea91 which includes #2206 works with both `{"ignore_metadata": True}` and `False` when the data is written with `preserve_index=False`. Both `True` and `False` also work when writing the data *without* setting `preserve_index=False`. 

All four situations produce a dataframe with a rangeindex that is correct. So it looks like pyarrow is interpreting the metadata correctly. 

I believe read parquet inside wrangler is no longer attempting to construct its own index, is that correct? Leaving it to the underlying library is probably best.

```
wr.s3.read_parquet(path, boto3_session=s3_session, pyarrow_additional_kwargs={"ignore_metadata": False})
wr.s3.read_parquet(path, boto3_session=s3_session, pyarrow_additional_kwargs={"ignore_metadata": True})
```

**Comment by jaidisido** [comment]
That is correct @jmahlik, index construction is delegated to arrow instead. Please feel free to close this if no more concerns, thanks!
