### ISSUE TITLE
Unable to open excel files from s3 with UTFDecodeError

### ISSUE THREAD

**Issue by bobthemighty** [aws/aws-sdk-pandas#2533]
### Describe the bug

When I try to read an excel file from s3, it blows up,

I _can_ read the same file from local disk.

```
>>> import awswrangler as wr
>>> df = wr.s3.read_csv("s3://$MY_BUCKET/LabData.xlsx")

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bob/.pyenv/versions/carbo-pants/lib64/python3.9/site-packages/awswrangler/_utils.py", line 176, in inner
    return func(*args, **kwargs)
  File "/home/bob/.pyenv/versions/carbo-pants/lib64/python3.9/site-packages/awswrangler/s3/_read_text.py", line 293, in read_csv
    return _read_text_format(
  File "/home/bob/.pyenv/versions/carbo-pants/lib64/python3.9/site-packages/awswrangler/s3/_read_text.py", line 132, in _read_text_format
    return _read_text(
  File "/home/bob/.pyenv/versions/carbo-pants/lib64/python3.9/site-packages/awswrangler/_distributed.py", line 105, in wrapper
    return cls.dispatch_func(func)(*args, **kw)
  File "/home/bob/.pyenv/versions/carbo-pants/lib64/python3.9/site-packages/awswrangler/s3/_read_text.py", line 58, in _read_text
    tables = executor.map(
  File "/home/bob/.pyenv/versions/carbo-pants/lib64/python3.9/site-packages/awswrangler/_executor.py", line 51, in map
    return list(self._exec.map(func, *iterables))
  File "/usr/lib64/python3.9/concurrent/futures/_base.py", line 609, in result_iterator
    yield fs.pop().result()
  File "/usr/lib64/python3.9/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/usr/lib64/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/usr/lib64/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/bob/.pyenv/versions/carbo-pants/lib64/python3.9/site-packages/awswrangler/s3/_read_text_core.py", line 112, in _read_text_file
    df: pd.DataFrame = parser_func(f, **pandas_kwargs)
  File "/home/bob/.pyenv/versions/carbo-pants/lib64/python3.9/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/home/bob/.pyenv/versions/carbo-pants/lib64/python3.9/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/home/bob/.pyenv/versions/carbo-pants/lib64/python3.9/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/bob/.pyenv/versions/carbo-pants/lib64/python3.9/site-packages/pandas/io/parsers/readers.py", line 605, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/bob/.pyenv/versions/carbo-pants/lib64/python3.9/site-packages/pandas/io/parsers/readers.py", line 1442, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/bob/.pyenv/versions/carbo-pants/lib64/python3.9/site-packages/pandas/io/parsers/readers.py", line 1753, in _make_engine
    return mapping[engine](f, **self.options)
  File "/home/bob/.pyenv/versions/carbo-pants/lib64/python3.9/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 79, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 547, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 636, in pandas._libs.parsers.TextReader._get_header
  File "pandas/_libs/parsers.pyx", line 852, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1965, in pandas._libs.parsers.raise_parser_error
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xde in position 16: invalid continuation byte

>>> import pandas as pd
>>> pd.read_excel("/tmp/lab-data.xlsx")
                    Date  free lime   SiO2  Al2O3  Fe2O3    CaO   MgO   K2O  Na2O     SO3      Cl  ...    C3Ab   C3Sd  M1-C3S  M3-C3S   C2Sd  C3Acd  C3Aod  C4AFd  Ca(OH)2  MgOc  K2SO4
0    2021-02-28 15:30:00       1.12  20.93   4.87   3.22  64.98  1.59  0.85  0.24  0.8269  0.2250  ...  7.4592  63.64   31.18   32.46  15.23   1.77   3.63  10.79     0.46  0.91   0.76
1    2021-02-28 16:30:00       0.76  21.24   5.11   3.39  66.12  1.60  0.48  0.23  0.6650  0.0853  ...  7.8077  64.68   31.69   32.99  14.51   2.89   2.55  11.80     0.00  0.73   0.00
2    2021-02-28 17:30:00       0.66  21.46   5.26   3.49  66.86  1.62  0.36  0.23  0.4739  0.0386  ...  8.0360  66.48   31.25   35.24  12.91   2.64   2.72  12.07     0.00  0.76   0.00
3    2021-02-28 18:30:00       1.21  21.37   5.03   3.41  66.15  1.56  0.76  0.28  0.3660  0.0211  ...  7.5618  67.79   21.69   46.09  12.15   2.55   3.71  10.14     0.00  0.73   0.00
4    2021-02-28 19:30:00       1.58  21.51   5.02   3.37  66.35  1.62  0.73  0.25  0.4595  0.0227  ...  7.6030  66.22   35.76   30.46  13.92   2.45   3.54   9.35     0.00  0.88   0.00
...                  ...        ...    ...    ...    ...    ...   ...   ...   ...     ...     ...  ...     ...    ...     ...     ...    ...    ...    ...    ...      ...   ...    ...
9266 2023-10-16 00:15:00       1.74  20.85   5.12   3.80  66.02  1.68  0.81  0.17  0.7211  0.0145  ...  7.1404  58.25     NaN     NaN  15.30   5.98   0.97  13.02     0.78  0.75   0.64
9267 2023-10-16 02:15:00       1.92  20.89   5.09   3.77  65.70  1.63  0.93  0.18  0.8281  0.0152  ...  7.1117  58.93     NaN     NaN  15.94   4.32   1.65  14.53     0.34  0.85   0.74
9268 2023-10-16 04:15:00       1.98  20.94   5.08   3.78  65.91  1.62  0.84  0.16  0.7893  0.0153  ...  7.0683  55.51     NaN     NaN  17.85   5.85   0.90  12.53     0.88  0.84   1.52
9269 2023-10-16 06:15:00       2.02  21.07   5.07   3.74  66.06  1.63  0.81  0.15  0.7521  0.0173  ...  7.1094  55.92     NaN     NaN  17.53   6.03   0.91  12.76     0.88  0.71   0.93
9270 2023-10-16 08:15:00       1.71  21.13   4.97   3.70  65.96  1.63  0.84  0.16  0.7724  0.0166  ...  6.9121  56.62     NaN     NaN  16.83   6.00   0.83  12.53     0.79  0.74   1.59

[9271 rows x 29 columns]
>>>
```

### How to Reproduce

```
import awswrangler as wr
wr.s3.read_excel(some_s3_url)
```

### Expected behavior

It should read the csv file.

### OS

Linux

### Python version

3.9.18

### AWS SDK for pandas version

3.4.2

### Additional context

I tried opening the file from disk with the filename after reading [this SO](https://stackoverflow.com/questions/48647122/pandas-read-excel-utf-8-codec-cant-decode-byte-0xa8-in-position-14-invalid) post.

**Comment by jaidisido** [comment]
I am slightly confused, your example is showing `wr.s3.read_csv` instead of `read_excel`? Is that just a typo or did you really intend to use `read_csv` for an Excel (because that won't work)

Under the hood, `wr.s3.read_excel` just uses the [pandas](https://github.com/aws/aws-sdk-pandas/blob/main/awswrangler/s3/_read_excel.py#L93) method, so it should work in a similar fashion

**Comment by bobthemighty** [comment]
That is the most embarassing GH issue I have ever opened.
