### ISSUE TITLE
"Got s3 uri but arrow compiled without s3 support"

### ISSUE THREAD

**Issue by ragurajesh** [aws/aws-sdk-pandas#2546]
### Describe the bug

The below lambda code with pd.DataFrame.to_parquet in  S3 was working fine in python 3.7 , now migrating the same to 3.11 with layer AWSSDKPandas-Python311 version 3.

### How to Reproduce

```
*P.S. Please do not attach files as it's considered a security risk. Add code snippets directly in the message body as much as possible.*
```
The below lambda code was working fine in python 3.7 , now migrating the same to 3.11 with layer AWSSDKPandas-Python311 version 3.

key = event['Key']
tname = key.split('/')[-2]
last_modified = (obj.last_modified).replace(tzinfo=None)
flist = {'cr_web_countries': 'F_Fetch_Crty_WS',
                 'rag_skus': 'F_Fetch_SKU_ATTR'}
data = [[flist[tname], tname, last_modified ]]
df = pd.DataFrame(data, columns=['Function_Name', 'Table_Name', 'Last_Modified'])
df.to_parquet(path=s3_url, engine='auto', index=False)

Error:

[ERROR] ArrowNotImplementedError: Got S3 URI but Arrow compiled without S3 support
Traceback (most recent call last):
  File "/var/task/AttributeDeltaLambda.py", line 123, in lambda_handler
    raise err
  File "/var/task/AttributeDeltaLambda.py", line 116, in lambda_handler
    df.to_parquet(path=s3_url, engine='pyarrow', index=False)
  File "/opt/python/pandas/core/frame.py", line 2970, in to_parquet
    return to_parquet(
  File "/opt/python/pandas/io/parquet.py", line 483, in to_parquet
    impl.write(
  File "/opt/python/pandas/io/parquet.py", line 197, in write
    path_or_handle, handles, filesystem = _get_path_or_handle(
  File "/opt/python/pandas/io/parquet.py", line 116, in _get_path_or_handle
    fs, path_or_handle = pa_fs.FileSystem.from_uri(path)
  File "pyarrow/_fs.pyx", line 470, in pyarrow._fs.FileSystem.from_uri
  File "pyarrow/error.pxi", line 144, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 121, in pyarrow.lib.check_status

### Expected behavior

expected to create .parquets file in s3

### OS

lambda

### Python version

3.11

### AWS SDK for pandas version

2 and 3

**Comment by ragurajesh** [comment]
For more clarity , added the below code...

key = event['Key']
tname = key.split('/')[-2]
dest_key = 'attribute-delta-files/'+tname+'/'+key.split('/')[-1]

for obj in src_bucket.objects.filter(Prefix=dest_key):
                print((obj.last_modified).replace(tzinfo=None))

last_modified = (obj.last_modified).replace(tzinfo=None)

flist = {'cr_web_countries': 'F_Fetch_Crty_WS',
'rag_skus': 'F_Fetch_SKU_ATTR'}
data = [[flist[tname], tname, last_modified ]]
df = pd.DataFrame(data, columns=['Function_Name', 'Table_Name', 'Last_Modified'])
df.to_parquet(path=s3_url, engine='auto', index=False)

**Comment by jaidisido** [comment]
The code you shared uses the pandas to_parquet API. Our layers are tested and meant to be used with our library's (awswrangler) APIs.

I suggest you replace:
```python
df.to_parquet(path=s3_url, engine='auto', index=False)
```
with
```python
wr.s3.to_parquet(df=df, path=s3_url, index=False)
```

**Comment by ragurajesh** [comment]
it looks fine using the above recommended api. Thanks Much.
