### ISSUE TITLE
Bug in python 3.12 layer

### ISSUE THREAD

**Issue by aarana95** [aws/aws-sdk-pandas#2603]
### Describe the bug

I've seen the layer arn:aws:lambda:eu-west-1:336392948345:layer:AWSSDKPandas-Python312:1 in https://github.com/aws/aws-sdk-pandas/pull/2602 PR, and I have a bug importing awswrangler

```
[ERROR] OSError: Could not find lib geos_c or load any of its variants ['libgeos_c.so.1', 'libgeos_c.so'].
Traceback (most recent call last):  
File "/var/lang/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1325, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 929, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed  
....  in <module>
    import awswrangler as wr
  File "/opt/python/awswrangler/__init__.py", line 10, in <module>
    from awswrangler import (
  File "/opt/python/awswrangler/athena/__init__.py", line 15, in <module>
    from awswrangler.athena._read import (
  File "/opt/python/awswrangler/athena/_read.py", line 35, in <module>
    shapely_wkt = _utils.import_optional_dependency("shapely.wkt")
  File "/opt/python/awswrangler/_utils.py", line 147, in import_optional_dependency
    module = importlib.import_module(name)
  File "/var/lang/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/tmp/sls-py-req/shapely/wkt.py", line 6, in <module>
    from shapely import geos
  File "/tmp/sls-py-req/shapely/geos.py", line 100, in <module>
    _lgeos = load_dll('geos_c', fallbacks=alt_paths)
  File "/tmp/sls-py-req/shapely/geos.py", line 54, in load_dll
    raise OSError(
```

### How to Reproduce

Bug in AWS lambda with python 3.12, I use `arn:aws:lambda:eu-west-1:017000801446:layer:AWSLambdaPowertoolsPythonV2:59` layer too

### OS

Amazon Linux 2023

### Python version

3.12

### AWS SDK for pandas version

lastest

**Comment by kukushking** [comment]
Looking closely at the error, it looks like the runtime you are using is missing `['libgeos_c.so.1', 'libgeos_c.so']`. Are there any other layers that may be vending geopandas/shapely but not the required c libs?

iIt doesn't look like it's powertools either, because the error still does not reproduce with both layers in place.

**Comment by aarana95** [comment]
Yes, sorry... was shapely
