### ISSUE TITLE
Pyarrow 15.0.0 breaking changes

### ISSUE THREAD

**Issue by aram-eskandari** [aws/aws-sdk-pandas#2633]
### Describe the bug

PyArrow 15.0.0 is out, and that currently breaks awswrangler in python. 

Simply importing the package gives this error message:
`AttributeError: module 'pyarrow.parquet' has no attribute 'ParquetPartitions'`

### How to Reproduce

To reproduce this error:

Upgrade pyarrow to 15.0.0
`pip install --upgrade pyarrow`

Run a simple python script
```
python
import awswrangler
```

### Expected behavior

I should be able to use not freeze a pyarrow version and still be able to `import awswrangler`. Currently I have to freeze it to `14.X.X`.

### OS

Mac

### Python version

9.3.13

### AWS SDK for pandas version

awswrangler 3.4.0, pandas 2.1.0

**Comment by mauro-mascia** [comment]
You must update awswrangler to the last 3.5.1

**Comment by aram-eskandari** [comment]
worked perfectly, thank you!

**Comment by Gatsby-Lee** [comment]
@aram-eskandari 
how did it fix your issue?
it seems the issue is not really fixed on 3.5.1 or 3.5.2

The pyarrow 15.0.0 is installed and it cause this error
```
  File "/usr/local/lib/python3.9/site-packages/awswrangler/__init__.py", line 10, in <module>
    from awswrangler import (  # noqa
  File "/usr/local/lib/python3.9/site-packages/awswrangler/athena/__init__.py", line 3, in <module>
    from awswrangler.athena._executions import (  # noqa
  File "/usr/local/lib/python3.9/site-packages/awswrangler/athena/_executions.py", line 17, in <module>
    from awswrangler import _utils, exceptions, typing
  File "/usr/local/lib/python3.9/site-packages/awswrangler/_utils.py", line 40, in <module>
    from awswrangler._arrow import _table_to_df
  File "/usr/local/lib/python3.9/site-packages/awswrangler/_arrow.py", line 12, in <module>
    from awswrangler._data_types import athena2pyarrow
  File "/usr/local/lib/python3.9/site-packages/awswrangler/_data_types.py", line 695, in <module>
    partitions: Optional[pyarrow.parquet.ParquetPartitions],
AttributeError: module 'pyarrow.parquet' has no attribute 'ParquetPartitions'
```

```
pip list
Package           Version
----------------- ------------
awswrangler       3.5.1
boto3             1.34.29
botocore          1.34.29
jmespath          1.0.1
numpy             1.26.3
packaging         23.2
pandas            2.2.0
pip               22.0.4
pyarrow           15.0.0
python-dateutil   2.8.2
pytz              2023.3.post1
s3transfer        0.10.0
setuptools        58.1.0
six               1.16.0
typing_extensions 4.9.0
tzdata            2023.4
urllib3           1.26.18
```
```
Python 3.9.12 (main, May 28 2022, 23:59:03) 
[Clang 13.1.6 (clang-1316.0.21.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyarrow.parquet
>>> pyarrow.parquet.ParquetPartitions
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'pyarrow.parquet' has no attribute 'ParquetPartitions'
```

**Comment by Gatsby-Lee** [comment]
I documented about this issue.
https://medium.com/p/d570af14a594

**Comment by kukushking** [comment]
Hi @Gatsby-Lee this was addressed in https://github.com/aws/aws-sdk-pandas/pull/2649 and will be available in the next release.

**Comment by Gatsby-Lee** [comment]
@kukushking oh. great. Thank you!!

**Comment by wang-dingping** [comment]
I tried the version 3.5.2, it failed. And i changed to the version 3.5.1, it worked out. It seemed to still have bug in version 3.5.2
