### ISSUE TITLE
Repeated s3.to_parquet writes with index=True raise InvalidSchemaConvergence on s3.read_parquet with validate_schema=True

### ISSUE THREAD

**Issue by robert-schmidtke** [aws/aws-sdk-pandas#2652]
### Describe the bug

When writing using `wr.s3.to_parquet(..., index=True, ...)` multiple times and reading the data back using `wr.s3.read_parquet(..., validate_schema=True, ...)`, an `InvalidSchemaConversion` is raised.

Find below the full environment.

<details>

```
# packages in environment at /home/rschmidtke/miniforge3/envs/wrangler35:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
aws-c-auth                0.7.11               h0b4cabd_1    conda-forge
aws-c-cal                 0.6.9                h14ec70c_3    conda-forge
aws-c-common              0.9.12               hd590300_0    conda-forge
aws-c-compression         0.2.17               h572eabf_8    conda-forge
aws-c-event-stream        0.4.1                h97bb272_2    conda-forge
aws-c-http                0.8.0                h9129f04_2    conda-forge
aws-c-io                  0.14.0               hf8f278a_1    conda-forge
aws-c-mqtt                0.10.1               h2b97f5f_0    conda-forge
aws-c-s3                  0.4.9                hca09fc5_0    conda-forge
aws-c-sdkutils            0.1.13               h572eabf_1    conda-forge
aws-checksums             0.1.17               h572eabf_7    conda-forge
aws-crt-cpp               0.26.0               h04327c0_8    conda-forge
aws-sdk-cpp               1.11.210            hba3e011_10    conda-forge
awswrangler               3.5.2              pyhd8ed1ab_0    conda-forge
black                     24.1.1          py311h38be061_0    conda-forge
boto3                     1.34.31            pyhd8ed1ab_0    conda-forge
botocore                  1.34.31            pyhd8ed1ab_0    conda-forge
brotli-python             1.1.0           py311hb755f60_1    conda-forge
bzip2                     1.0.8                hd590300_5    conda-forge
c-ares                    1.26.0               hd590300_0    conda-forge
ca-certificates           2023.11.17           hbcca054_0    conda-forge
click                     8.1.7           unix_pyh707e725_0    conda-forge
gflags                    2.2.2             he1b5a44_1004    conda-forge
glog                      0.6.0                h6f12383_0    conda-forge
icu                       73.2                 h59595ed_0    conda-forge
isort                     5.13.2             pyhd8ed1ab_0    conda-forge
jmespath                  1.0.1              pyhd8ed1ab_0    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
krb5                      1.21.2               h659d440_0    conda-forge
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
libabseil                 20230802.1      cxx17_h59595ed_0    conda-forge
libarrow                  14.0.2           h84dd17c_4_cpu    conda-forge
libarrow-acero            14.0.2           h59595ed_4_cpu    conda-forge
libarrow-dataset          14.0.2           h59595ed_4_cpu    conda-forge
libarrow-flight           14.0.2           hdc44a87_4_cpu    conda-forge
libarrow-flight-sql       14.0.2           hfbc7f12_4_cpu    conda-forge
libarrow-gandiva          14.0.2           hacb8726_4_cpu    conda-forge
libarrow-substrait        14.0.2           hfbc7f12_4_cpu    conda-forge
libblas                   3.9.0           21_linux64_openblas    conda-forge
libbrotlicommon           1.1.0                hd590300_1    conda-forge
libbrotlidec              1.1.0                hd590300_1    conda-forge
libbrotlienc              1.1.0                hd590300_1    conda-forge
libcblas                  3.9.0           21_linux64_openblas    conda-forge
libcrc32c                 1.1.2                h9c3ff4c_0    conda-forge
libcurl                   8.5.0                hca28451_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 hd590300_2    conda-forge
libevent                  2.1.12               hf998b51_1    conda-forge
libexpat                  2.5.0                hcb278e6_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 13.2.0               h807b86a_4    conda-forge
libgfortran-ng            13.2.0               h69a702a_4    conda-forge
libgfortran5              13.2.0               ha4646dd_4    conda-forge
libgomp                   13.2.0               h807b86a_4    conda-forge
libgoogle-cloud           2.12.0               hef10d8f_5    conda-forge
libgrpc                   1.60.0               h74775cd_1    conda-forge
libiconv                  1.17                 hd590300_2    conda-forge
liblapack                 3.9.0           21_linux64_openblas    conda-forge
libllvm15                 15.0.7               hb3ce162_4    conda-forge
libnghttp2                1.58.0               h47da74e_1    conda-forge
libnl                     3.9.0                hd590300_0    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libnuma                   2.0.16               h0b41bf4_1    conda-forge
libopenblas               0.3.26          pthreads_h413a1c8_0    conda-forge
libparquet                14.0.2           h352af49_4_cpu    conda-forge
libprotobuf               4.25.1               hf27288f_0    conda-forge
libre2-11                 2023.06.02           h7a70373_0    conda-forge
libsqlite                 3.44.2               h2797004_0    conda-forge
libssh2                   1.11.0               h0841786_0    conda-forge
libstdcxx-ng              13.2.0               h7e041cc_4    conda-forge
libthrift                 0.19.0               hb90f79a_1    conda-forge
libutf8proc               2.8.0                h166bdaf_0    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libxcrypt                 4.4.36               hd590300_1    conda-forge
libxml2                   2.12.4               h232c23b_1    conda-forge
libzlib                   1.2.13               hd590300_5    conda-forge
lz4-c                     1.9.4                hcb278e6_0    conda-forge
mypy_extensions           1.0.0              pyha770c72_0    conda-forge
ncurses                   6.4                  h59595ed_2    conda-forge
numpy                     1.26.3          py311h64a7726_0    conda-forge
openssl                   3.2.1                hd590300_0    conda-forge
orc                       1.9.2                h7829240_1    conda-forge
packaging                 23.2               pyhd8ed1ab_0    conda-forge
pandas                    2.2.0           py311h320fe9a_0    conda-forge
pathspec                  0.12.1             pyhd8ed1ab_0    conda-forge
pip                       23.3.2             pyhd8ed1ab_0    conda-forge
platformdirs              4.2.0              pyhd8ed1ab_0    conda-forge
pyarrow                   14.0.2          py311h39c9aba_4_cpu    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.11.7          hab00c5b_1_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-tzdata             2023.4             pyhd8ed1ab_0    conda-forge
python_abi                3.11                    4_cp311    conda-forge
pytz                      2023.4             pyhd8ed1ab_0    conda-forge
rdma-core                 50.0                 hd3aeb46_0    conda-forge
re2                       2023.06.02           h2873b5e_0    conda-forge
readline                  8.2                  h8228510_1    conda-forge
s2n                       1.4.1                h06160fa_0    conda-forge
s3transfer                0.10.0             pyhd8ed1ab_0    conda-forge
setuptools                69.0.3             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.1.10               h9fff704_0    conda-forge
tk                        8.6.13          noxft_h4845f30_101    conda-forge
typing-extensions         4.9.0                hd8ed1ab_0    conda-forge
typing_extensions         4.9.0              pyha770c72_0    conda-forge
tzdata                    2023d                h0c530f3_0    conda-forge
ucx                       1.15.0               h75e419f_3    conda-forge
urllib3                   1.26.18            pyhd8ed1ab_0    conda-forge
wheel                     0.42.0             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
zstd                      1.5.5                hfc55251_0    conda-forge
```

</details>

### How to Reproduce

```python
import awswrangler as wr
import boto3
import pandas as pd

PATH = "..."
DATABASE = "..."
TABLE = "..."

def main() -> None:
    boto3_session = boto3.Session(region_name="eu-central-1")
    df = pd.DataFrame({"idx": [1, 2, 3], "val": [1.0, 2.0, 3.0]})
    df = df.set_index("idx")

    for iteration in range(2):
        print("Iteration", iteration)

        wr.s3.to_parquet(
            df,
            path=PATH,
            index=True,
            boto3_session=boto3_session,
            dataset=True,
            database=DATABASE,
            table=TABLE,
        )

        wr.s3.read_parquet(path=PATH, boto3_session=boto3_session, validate_schema=True)


if __name__ == "__main__":
    main()

# Iteration 0
/home/rschmidtke/miniforge3/envs/wrangler35/lib/python3.11/site-packages/awswrangler/_distributed.py:104: FutureWarning: promote has been superseded by mode='default'.
  return cls.dispatch_func(func)(*args, **kw)
# Iteration 1
Traceback (most recent call last):
  File "/home/rschmidtke/workspace/sd/wranglertest/wranglertest.py", line 30, in <module>
    main()
  File "/home/rschmidtke/workspace/sd/wranglertest/wranglertest.py", line 26, in main
    wr.s3.read_parquet(path=path, boto3_session=boto3_session, validate_schema=True)
  File "/home/rschmidtke/miniforge3/envs/wrangler35/lib/python3.11/site-packages/awswrangler/_utils.py", line 178, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/rschmidtke/miniforge3/envs/wrangler35/lib/python3.11/site-packages/awswrangler/_config.py", line 735, in wrapper
    return function(**args)
           ^^^^^^^^^^^^^^^^
  File "/home/rschmidtke/miniforge3/envs/wrangler35/lib/python3.11/site-packages/awswrangler/s3/_read_parquet.py", line 499, in read_parquet
    schema = metadata_reader.validate_schemas(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rschmidtke/miniforge3/envs/wrangler35/lib/python3.11/site-packages/awswrangler/s3/_read.py", line 218, in validate_schemas
    schema = self._validate_schemas_from_files(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rschmidtke/miniforge3/envs/wrangler35/lib/python3.11/site-packages/awswrangler/s3/_read.py", line 204, in _validate_schemas_from_files
    return _validate_schemas(schemas, validate_schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rschmidtke/miniforge3/envs/wrangler35/lib/python3.11/site-packages/awswrangler/s3/_read.py", line 311, in _validate_schemas
    raise exceptions.InvalidSchemaConvergence(
awswrangler.exceptions.InvalidSchemaConvergence: At least 2 different schemas were detected:
    1 - val: double
-- schema metadata --
pandas: '{"index_columns": [], "column_indexes": [{"name": null, "field_n' + 301
    2 - val: double
idx: int64
-- schema metadata --
pandas: '{"index_columns": ["idx"], "column_indexes": [{"name": null, "fi' + 409.
```

### Expected behavior

The reads to succeed, as is the case with `awswrangler=3.4.2`, see the below the output of above script and environment it is run in.

```python
# Iteration 0
/home/rschmidtke/miniforge3/envs/wrangler34/lib/python3.11/site-packages/awswrangler/_distributed.py:105: FutureWarning: promote has been superseded by mode='default'.
  return cls.dispatch_func(func)(*args, **kw)
# Iteration 1
/home/rschmidtke/miniforge3/envs/wrangler34/lib/python3.11/site-packages/awswrangler/_distributed.py:105: FutureWarning: promote has been superseded by mode='default'.
  return cls.dispatch_func(func)(*args, **kw)
```

<details>

```
# packages in environment at /home/rschmidtke/miniforge3/envs/wrangler34:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
aws-c-auth                0.7.11               h0b4cabd_1    conda-forge
aws-c-cal                 0.6.9                h14ec70c_3    conda-forge
aws-c-common              0.9.12               hd590300_0    conda-forge
aws-c-compression         0.2.17               h572eabf_8    conda-forge
aws-c-event-stream        0.4.1                h97bb272_2    conda-forge
aws-c-http                0.8.0                h9129f04_2    conda-forge
aws-c-io                  0.14.0               hf8f278a_1    conda-forge
aws-c-mqtt                0.10.1               h2b97f5f_0    conda-forge
aws-c-s3                  0.4.9                hca09fc5_0    conda-forge
aws-c-sdkutils            0.1.13               h572eabf_1    conda-forge
aws-checksums             0.1.17               h572eabf_7    conda-forge
aws-crt-cpp               0.26.0               h04327c0_8    conda-forge
aws-sdk-cpp               1.11.210            hba3e011_10    conda-forge
awswrangler               3.4.2              pyhd8ed1ab_0    conda-forge
boto3                     1.34.31            pyhd8ed1ab_0    conda-forge
botocore                  1.34.31            pyhd8ed1ab_0    conda-forge
brotli-python             1.1.0           py311hb755f60_1    conda-forge
bzip2                     1.0.8                hd590300_5    conda-forge
c-ares                    1.26.0               hd590300_0    conda-forge
ca-certificates           2023.11.17           hbcca054_0    conda-forge
gflags                    2.2.2             he1b5a44_1004    conda-forge
glog                      0.6.0                h6f12383_0    conda-forge
icu                       73.2                 h59595ed_0    conda-forge
jmespath                  1.0.1              pyhd8ed1ab_0    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
krb5                      1.21.2               h659d440_0    conda-forge
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
libabseil                 20230802.1      cxx17_h59595ed_0    conda-forge
libarrow                  14.0.2           h84dd17c_4_cpu    conda-forge
libarrow-acero            14.0.2           h59595ed_4_cpu    conda-forge
libarrow-dataset          14.0.2           h59595ed_4_cpu    conda-forge
libarrow-flight           14.0.2           hdc44a87_4_cpu    conda-forge
libarrow-flight-sql       14.0.2           hfbc7f12_4_cpu    conda-forge
libarrow-gandiva          14.0.2           hacb8726_4_cpu    conda-forge
libarrow-substrait        14.0.2           hfbc7f12_4_cpu    conda-forge
libblas                   3.9.0           21_linux64_openblas    conda-forge
libbrotlicommon           1.1.0                hd590300_1    conda-forge
libbrotlidec              1.1.0                hd590300_1    conda-forge
libbrotlienc              1.1.0                hd590300_1    conda-forge
libcblas                  3.9.0           21_linux64_openblas    conda-forge
libcrc32c                 1.1.2                h9c3ff4c_0    conda-forge
libcurl                   8.5.0                hca28451_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 hd590300_2    conda-forge
libevent                  2.1.12               hf998b51_1    conda-forge
libexpat                  2.5.0                hcb278e6_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 13.2.0               h807b86a_4    conda-forge
libgfortran-ng            13.2.0               h69a702a_4    conda-forge
libgfortran5              13.2.0               ha4646dd_4    conda-forge
libgomp                   13.2.0               h807b86a_4    conda-forge
libgoogle-cloud           2.12.0               hef10d8f_5    conda-forge
libgrpc                   1.60.0               h74775cd_1    conda-forge
libiconv                  1.17                 hd590300_2    conda-forge
liblapack                 3.9.0           21_linux64_openblas    conda-forge
libllvm15                 15.0.7               hb3ce162_4    conda-forge
libnghttp2                1.58.0               h47da74e_1    conda-forge
libnl                     3.9.0                hd590300_0    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libnuma                   2.0.16               h0b41bf4_1    conda-forge
libopenblas               0.3.26          pthreads_h413a1c8_0    conda-forge
libparquet                14.0.2           h352af49_4_cpu    conda-forge
libprotobuf               4.25.1               hf27288f_0    conda-forge
libre2-11                 2023.06.02           h7a70373_0    conda-forge
libsqlite                 3.44.2               h2797004_0    conda-forge
libssh2                   1.11.0               h0841786_0    conda-forge
libstdcxx-ng              13.2.0               h7e041cc_4    conda-forge
libthrift                 0.19.0               hb90f79a_1    conda-forge
libutf8proc               2.8.0                h166bdaf_0    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libxcrypt                 4.4.36               hd590300_1    conda-forge
libxml2                   2.12.4               h232c23b_1    conda-forge
libzlib                   1.2.13               hd590300_5    conda-forge
lz4-c                     1.9.4                hcb278e6_0    conda-forge
ncurses                   6.4                  h59595ed_2    conda-forge
numpy                     1.26.3          py311h64a7726_0    conda-forge
openssl                   3.2.1                hd590300_0    conda-forge
orc                       1.9.2                h7829240_1    conda-forge
packaging                 23.2               pyhd8ed1ab_0    conda-forge
pandas                    2.2.0           py311h320fe9a_0    conda-forge
pip                       23.3.2             pyhd8ed1ab_0    conda-forge
pyarrow                   14.0.2          py311h39c9aba_4_cpu    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.11.7          hab00c5b_1_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-tzdata             2023.4             pyhd8ed1ab_0    conda-forge
python_abi                3.11                    4_cp311    conda-forge
pytz                      2023.4             pyhd8ed1ab_0    conda-forge
rdma-core                 50.0                 hd3aeb46_0    conda-forge
re2                       2023.06.02           h2873b5e_0    conda-forge
readline                  8.2                  h8228510_1    conda-forge
s2n                       1.4.1                h06160fa_0    conda-forge
s3transfer                0.10.0             pyhd8ed1ab_0    conda-forge
setuptools                69.0.3             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.1.10               h9fff704_0    conda-forge
tk                        8.6.13          noxft_h4845f30_101    conda-forge
typing-extensions         4.9.0                hd8ed1ab_0    conda-forge
typing_extensions         4.9.0              pyha770c72_0    conda-forge
tzdata                    2023d                h0c530f3_0    conda-forge
ucx                       1.15.0               h75e419f_3    conda-forge
urllib3                   1.26.18            pyhd8ed1ab_0    conda-forge
wheel                     0.42.0             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
zstd                      1.5.5                hfc55251_0    conda-forge
```

</details>

### OS

Ubuntu 20.04.6 LTS (WSL v2)

### Python version

Python 3.11.7

### AWS SDK for pandas version

awswrangler 3.5.2 pyhd8ed1ab_0 conda-forge

**Comment by robert-schmidtke** [comment]
Ran a bisect and it seems this PR is the culprit: https://github.com/aws/aws-sdk-pandas/pull/2528

```
commit 67efc064a359518b77288c7e52057d8ab1d1dc9c
Author: kukushking <kukushkin.anton@gmail.com>
Date:   Wed Nov 29 23:33:03 2023 +0000

    feat: Support partitioning by index cols (#2528)
```

I'll take a look, but maybe @kukushking already has an idea?

**Comment by robert-schmidtke** [comment]
My downstream tests are now succeeding, so I have put this PR back into ready for review.
