### ISSUE TITLE
Cloudwatch logs read_logs function breaks from version 3.4.0 onwards 

### ISSUE THREAD

**Issue by NachtBlade31** [aws/aws-sdk-pandas#2721]
### Describe the bug

I am trying to read the logs of multiple cloudwatch log groups. I was able to get the logs with the same piece of code till version 3.3.0 , but from 3.4.0 onwards, I am getting an error . The following error we get while executing a glue job in version 4.0
Please find the sample code below for which the error occurs:
```
session = boto3.session.Session(region_name='region-name')
log_groups = ['/project/client_workflow/abc1','/project/client_workflow/abc2','/project/client_workflow/abc3','/project/client_workflow/abc4','/project/client_workflow/abc5','/project/client_workflow/abc6','/project/client_workflow/abc7','/project/client_workflow/abc8','/project/client_workflow/abc9','/project/client_workflow/abc10','/project/client_workflow/abc11','/project/client_workflow/abc12','/project/client_workflow/abc13',]
logs = wr.cloudwatch.read_logs(
        # log_group_names=["/project/client_workflow/abc1"],
        log_group_names=log_groups,
        query="fields @timestamp, @message, @logStream | sort @timestamp desc",
        boto3_session=session
    )
```
The Following code breaks from version 3.4.0 onwards with the following error :
```
2024-03-13 08:41:36,489 ERROR [main] glue.ProcessLauncher (Logging.scala:logError(77)): Error from Python:Traceback (most recent call last):
  File "/tmp/filename.py", line 1011, in <module>
    pii_df = functionname()
  File "/tmp/filename.py", line 409, in functionname
    logs = wr.cloudwatch.read_logs(
  File "/home/spark/.local/lib/python3.10/site-packages/awswrangler/cloudwatch.py", line 244, in read_logs
    results: List[List[Dict[str, str]]] = run_query(
  File "/home/spark/.local/lib/python3.10/site-packages/awswrangler/cloudwatch.py", line 191, in run_query
    query_id: str = start_query(
  File "/home/spark/.local/lib/python3.10/site-packages/awswrangler/cloudwatch.py", line 96, in start_query
    response = client_logs.start_query(**args)
  File "/home/spark/.local/lib/python3.10/site-packages/botocore/client.py", line 514, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/spark/.local/lib/python3.10/site-packages/botocore/client.py", line 901, in _make_api_call
    request_dict = self._convert_to_request_dict(
  File "/home/spark/.local/lib/python3.10/site-packages/botocore/client.py", line 962, in _convert_to_request_dict
    request_dict = self._serializer.serialize_to_request(
  File "/home/spark/.local/lib/python3.10/site-packages/botocore/validate.py", line 381, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Unknown parameter in input: "logGroupIdentifiers", must be one of: logGroupName, logGroupNames, startTime, endTime, queryString, limit
```
Upon seeing the release logs and comparing the diff for 3.3.0 and 3.4.0 , I can see that there were changes in the file which is directly causing these breaks .
Can you please check on this on priority basis . 

### How to Reproduce

Please find the sample code below for which the error occurs:

```
session = boto3.session.Session(region_name='region-name')
log_groups = ['/project/client_workflow/abc1','/project/client_workflow/abc2','/project/client_workflow/abc3','/project/client_workflow/abc4','/project/client_workflow/abc5','/project/client_workflow/abc6','/project/client_workflow/abc7','/project/client_workflow/abc8','/project/client_workflow/abc9','/project/client_workflow/abc10','/project/client_workflow/abc11','/project/client_workflow/abc12','/project/client_workflow/abc13',]
logs = wr.cloudwatch.read_logs(
        # log_group_names=["/project/client_workflow/abc1"],
        log_group_names=log_groups,
        query="fields @timestamp, @message, @logStream | sort @timestamp desc",
        boto3_session=session
    )

```

### OS

Glue 4.0  - Python 3 , Spark 3.3

### Python version

python 3.10

### AWS SDK for pandas version

3.4.0

**Comment by jaidisido** [comment]
`logGroupIdentifiers` has indeed replaced `logGroupNames` following #2429 and #2430. I believe the default boto3 and botocore versions installed on Glue spark jobs are pretty old and do not recognise this new parameter to this API. My suggestion would be to [upgrade](https://docs.aws.amazon.com/glue/latest/dg/aws-glue-programming-python-libraries.html#addl-python-modules-support) them to a new version. Something along the lines of:
```
"--additional-python-modules", "botocore>=1.29.152,boto3>=1.26.152"
```

**Comment by NachtBlade31** [comment]
Thanks for the prompt response. I will try to upgrade the botocore and boto3 libs and check the same
